// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/product/insert": {
            "post": {
                "description": "Insert multiple products into the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "Insert products",
                "parameters": [
                    {
                        "description": "Product Insert Request",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ProductInsertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ProductInsertResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.ProductFailToInsert": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "@inject_tag: json:\"id\" form:\"id\"",
                    "type": "integer"
                },
                "introduction": {
                    "description": "@inject_tag: json:\"introduction\" form:\"introduction\"",
                    "type": "string"
                },
                "msg": {
                    "description": "@inject_tag: json:\"msg\" form:\"msg\"",
                    "type": "string"
                },
                "name": {
                    "description": "@inject_tag: json:\"name\" form:\"name\"",
                    "type": "string"
                },
                "note": {
                    "description": "@inject_tag: json:\"note\" form:\"note\"",
                    "type": "string"
                },
                "price": {
                    "description": "@inject_tag: json:\"price\" form:\"price\"",
                    "type": "number"
                },
                "producer_id": {
                    "description": "@inject_tag: json:\"producer_id\" form:\"producer_id\"",
                    "type": "integer"
                }
            }
        },
        "service.ProductInsertRequest": {
            "type": "object",
            "properties": {
                "product": {
                    "description": "@inject_tag: json:\"product\" form:\"product\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProductModel"
                    }
                }
            }
        },
        "service.ProductInsertResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "@inject_tag: json:\"code\" form:\"code\"",
                    "type": "integer"
                },
                "fail_list": {
                    "description": "@inject_tag: json:\"fail_list\" form:\"fail_list\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProductFailToInsert"
                    }
                },
                "msg": {
                    "description": "@inject_tag: json:\"msg\" form:\"msg\"",
                    "type": "string"
                },
                "success_list": {
                    "description": "@inject_tag: json:\"success_list\" form:\"success_list\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProductModel"
                    }
                }
            }
        },
        "service.ProductModel": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "@inject_tag: json:\"id\" form:\"id\"",
                    "type": "integer"
                },
                "introduction": {
                    "description": "@inject_tag: json:\"introduction\" form:\"introduction\"",
                    "type": "string"
                },
                "name": {
                    "description": "@inject_tag: json:\"name\" form:\"name\"",
                    "type": "string"
                },
                "note": {
                    "description": "@inject_tag: json:\"note\" form:\"note\"",
                    "type": "string"
                },
                "price": {
                    "description": "@inject_tag: json:\"price\" form:\"price\"",
                    "type": "number"
                },
                "producer_id": {
                    "description": "@inject_tag: json:\"producer_id\" form:\"producer_id\"",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "超市进销存系统--数据库课设接口文档",
	Description:      "没有描述",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
