// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: employeeService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmployeeModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"name" form:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" form:"name"`
	// @gotags: json:"tel" form:"tel"
	Tel string `protobuf:"bytes,2,opt,name=tel,proto3" json:"tel" form:"tel"`
	// @gotags: json:"salary" form:"salary"
	Salary float64 `protobuf:"fixed64,3,opt,name=salary,proto3" json:"salary" form:"salary"`
	// @gotags: json:"note" form:"note"
	Note string `protobuf:"bytes,4,opt,name=note,proto3" json:"note" form:"note"`
	// @gotags: json:"level" form:"level"
	Level int32 `protobuf:"varint,5,opt,name=level,proto3" json:"level" form:"level"`
}

func (x *EmployeeModel) Reset() {
	*x = EmployeeModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employeeService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeModel) ProtoMessage() {}

func (x *EmployeeModel) ProtoReflect() protoreflect.Message {
	mi := &file_employeeService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeModel.ProtoReflect.Descriptor instead.
func (*EmployeeModel) Descriptor() ([]byte, []int) {
	return file_employeeService_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeeModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmployeeModel) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *EmployeeModel) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *EmployeeModel) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *EmployeeModel) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type EmployeeSignupSuccessModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" form:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
	// @gotags: json:"account" form:"account"
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account" form:"account"`
	// @gotags: json:"password" form:"password"
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password" form:"password"`
	// @gotags: json:"name" form:"name"
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name" form:"name"`
	// @gotags: json:"tel" form:"tel"
	Tel string `protobuf:"bytes,5,opt,name=tel,proto3" json:"tel" form:"tel"`
	// @gotags: json:"salary" form:"salary"
	Salary float64 `protobuf:"fixed64,6,opt,name=salary,proto3" json:"salary" form:"salary"`
	// @gotags: json:"note" form:"note"
	Note string `protobuf:"bytes,7,opt,name=note,proto3" json:"note" form:"note"`
	// @gotags: json:"level" form:"level"
	Level int32 `protobuf:"varint,8,opt,name=level,proto3" json:"level" form:"level"`
}

func (x *EmployeeSignupSuccessModel) Reset() {
	*x = EmployeeSignupSuccessModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employeeService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeSignupSuccessModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeSignupSuccessModel) ProtoMessage() {}

func (x *EmployeeSignupSuccessModel) ProtoReflect() protoreflect.Message {
	mi := &file_employeeService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeSignupSuccessModel.ProtoReflect.Descriptor instead.
func (*EmployeeSignupSuccessModel) Descriptor() ([]byte, []int) {
	return file_employeeService_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeSignupSuccessModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmployeeSignupSuccessModel) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *EmployeeSignupSuccessModel) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EmployeeSignupSuccessModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmployeeSignupSuccessModel) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *EmployeeSignupSuccessModel) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *EmployeeSignupSuccessModel) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *EmployeeSignupSuccessModel) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type EmployeeSignupFailModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" form:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
	// @gotags: json:"name" form:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" form:"name"`
	// @gotags: json:"tel" form:"tel"
	Tel string `protobuf:"bytes,3,opt,name=tel,proto3" json:"tel" form:"tel"`
	// @gotags: json:"salary" form:"salary"
	Salary float64 `protobuf:"fixed64,4,opt,name=salary,proto3" json:"salary" form:"salary"`
	// @gotags: json:"note" form:"note"
	Note string `protobuf:"bytes,5,opt,name=note,proto3" json:"note" form:"note"`
	// @gotags: json:"level" form:"level"
	Level int32 `protobuf:"varint,6,opt,name=level,proto3" json:"level" form:"level"`
	// @gotags: json:"wrong_message" form:"wrong_message"
	WrongMessage string `protobuf:"bytes,7,opt,name=wrong_message,json=wrongMessage,proto3" json:"wrong_message" form:"wrong_message"`
}

func (x *EmployeeSignupFailModel) Reset() {
	*x = EmployeeSignupFailModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employeeService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeSignupFailModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeSignupFailModel) ProtoMessage() {}

func (x *EmployeeSignupFailModel) ProtoReflect() protoreflect.Message {
	mi := &file_employeeService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeSignupFailModel.ProtoReflect.Descriptor instead.
func (*EmployeeSignupFailModel) Descriptor() ([]byte, []int) {
	return file_employeeService_proto_rawDescGZIP(), []int{2}
}

func (x *EmployeeSignupFailModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmployeeSignupFailModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmployeeSignupFailModel) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *EmployeeSignupFailModel) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *EmployeeSignupFailModel) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *EmployeeSignupFailModel) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EmployeeSignupFailModel) GetWrongMessage() string {
	if x != nil {
		return x.WrongMessage
	}
	return ""
}

type EmployeeSignupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: name:"employee_list" json:"employee_list" form:"employee_list" uri:"employee_list"
	EmployeeList []*EmployeeModel `protobuf:"bytes,1,rep,name=employee_list,json=employeeList,proto3" json:"employee_list" name:"employee_list" form:"employee_list" uri:"employee_list"`
	// @gotags: name:"token" json:"token" form:"token" uri:"token"
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token" name:"token" form:"token" uri:"token"`
}

func (x *EmployeeSignupRequest) Reset() {
	*x = EmployeeSignupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employeeService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeSignupRequest) ProtoMessage() {}

func (x *EmployeeSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employeeService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeSignupRequest.ProtoReflect.Descriptor instead.
func (*EmployeeSignupRequest) Descriptor() ([]byte, []int) {
	return file_employeeService_proto_rawDescGZIP(), []int{3}
}

func (x *EmployeeSignupRequest) GetEmployeeList() []*EmployeeModel {
	if x != nil {
		return x.EmployeeList
	}
	return nil
}

func (x *EmployeeSignupRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EmployeeSignupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: name:"success_list" json:"success_list" form:"success_list" uri:"success_list"
	SuccessList []*EmployeeSignupSuccessModel `protobuf:"bytes,1,rep,name=success_list,json=successList,proto3" json:"success_list" name:"success_list" form:"success_list" uri:"success_list"`
	// @gotags: name:"fail_list" json:"fail_list" form:"fail_list" uri:"fail_list"
	FailList []*EmployeeSignupFailModel `protobuf:"bytes,2,rep,name=fail_list,json=failList,proto3" json:"fail_list" name:"fail_list" form:"fail_list" uri:"fail_list"`
	// @gotags: name:"code" json:"code" form:"code" uri:"code"
	Code uint32 `protobuf:"varint,3,opt,name=code,proto3" json:"code" name:"code" form:"code" uri:"code"`
}

func (x *EmployeeSignupResponse) Reset() {
	*x = EmployeeSignupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employeeService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeSignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeSignupResponse) ProtoMessage() {}

func (x *EmployeeSignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employeeService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeSignupResponse.ProtoReflect.Descriptor instead.
func (*EmployeeSignupResponse) Descriptor() ([]byte, []int) {
	return file_employeeService_proto_rawDescGZIP(), []int{4}
}

func (x *EmployeeSignupResponse) GetSuccessList() []*EmployeeSignupSuccessModel {
	if x != nil {
		return x.SuccessList
	}
	return nil
}

func (x *EmployeeSignupResponse) GetFailList() []*EmployeeSignupFailModel {
	if x != nil {
		return x.FailList
	}
	return nil
}

func (x *EmployeeSignupResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type EmployeeLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: name:"account" json:"account" form:"account" uri:"account"
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account" name:"account" form:"account" uri:"account"`
	// @gotags: name:"password" json:"password" form:"password" uri:"password"
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password" name:"password" form:"password" uri:"password"`
}

func (x *EmployeeLoginRequest) Reset() {
	*x = EmployeeLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employeeService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeLoginRequest) ProtoMessage() {}

func (x *EmployeeLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employeeService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeLoginRequest.ProtoReflect.Descriptor instead.
func (*EmployeeLoginRequest) Descriptor() ([]byte, []int) {
	return file_employeeService_proto_rawDescGZIP(), []int{5}
}

func (x *EmployeeLoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *EmployeeLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EmployeeLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: name:"id" json:"id" form:"id" uri:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" name:"id" form:"id" uri:"id"`
	// @gotags: name:"token" json:"token" form:"token" uri:"token"
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token" name:"token" form:"token" uri:"token"`
	// @gotags: name:"code" json:"code" form:"code" uri:"code"
	Code uint32 `protobuf:"varint,3,opt,name=code,proto3" json:"code" name:"code" form:"code" uri:"code"`
}

func (x *EmployeeLoginResponse) Reset() {
	*x = EmployeeLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employeeService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeLoginResponse) ProtoMessage() {}

func (x *EmployeeLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employeeService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeLoginResponse.ProtoReflect.Descriptor instead.
func (*EmployeeLoginResponse) Descriptor() ([]byte, []int) {
	return file_employeeService_proto_rawDescGZIP(), []int{6}
}

func (x *EmployeeLoginResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmployeeLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EmployeeLoginResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_employeeService_proto protoreflect.FileDescriptor

var file_employeeService_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x22, 0x77, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xca, 0x01, 0x0a, 0x1a, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x74, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xb6, 0x01, 0x0a, 0x17, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x46, 0x61, 0x69, 0x6c, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x6c,
	0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x77,
	0x72, 0x6f, 0x6e, 0x67, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x77, 0x72, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x6b, 0x0a, 0x15, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x65, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0c, 0x65, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xb5, 0x01,
	0x0a, 0x16, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0b, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x3e, 0x0a, 0x09, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x46, 0x61,
	0x69, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x4c, 0x0a, 0x14, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x51, 0x0a, 0x15, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0xb8, 0x01, 0x0a, 0x0f, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x1f, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x50, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_employeeService_proto_rawDescOnce sync.Once
	file_employeeService_proto_rawDescData = file_employeeService_proto_rawDesc
)

func file_employeeService_proto_rawDescGZIP() []byte {
	file_employeeService_proto_rawDescOnce.Do(func() {
		file_employeeService_proto_rawDescData = protoimpl.X.CompressGZIP(file_employeeService_proto_rawDescData)
	})
	return file_employeeService_proto_rawDescData
}

var file_employeeService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_employeeService_proto_goTypes = []any{
	(*EmployeeModel)(nil),              // 0: services.EmployeeModel
	(*EmployeeSignupSuccessModel)(nil), // 1: services.EmployeeSignupSuccessModel
	(*EmployeeSignupFailModel)(nil),    // 2: services.EmployeeSignupFailModel
	(*EmployeeSignupRequest)(nil),      // 3: services.EmployeeSignupRequest
	(*EmployeeSignupResponse)(nil),     // 4: services.EmployeeSignupResponse
	(*EmployeeLoginRequest)(nil),       // 5: services.EmployeeLoginRequest
	(*EmployeeLoginResponse)(nil),      // 6: services.EmployeeLoginResponse
}
var file_employeeService_proto_depIdxs = []int32{
	0, // 0: services.EmployeeSignupRequest.employee_list:type_name -> services.EmployeeModel
	1, // 1: services.EmployeeSignupResponse.success_list:type_name -> services.EmployeeSignupSuccessModel
	2, // 2: services.EmployeeSignupResponse.fail_list:type_name -> services.EmployeeSignupFailModel
	3, // 3: services.EmployeeService.EmployeeSignup:input_type -> services.EmployeeSignupRequest
	5, // 4: services.EmployeeService.EmployeeLogin:input_type -> services.EmployeeLoginRequest
	4, // 5: services.EmployeeService.EmployeeSignup:output_type -> services.EmployeeSignupResponse
	6, // 6: services.EmployeeService.EmployeeLogin:output_type -> services.EmployeeLoginResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_employeeService_proto_init() }
func file_employeeService_proto_init() {
	if File_employeeService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_employeeService_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employeeService_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeSignupSuccessModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employeeService_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeSignupFailModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employeeService_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeSignupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employeeService_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeSignupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employeeService_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employeeService_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_employeeService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employeeService_proto_goTypes,
		DependencyIndexes: file_employeeService_proto_depIdxs,
		MessageInfos:      file_employeeService_proto_msgTypes,
	}.Build()
	File_employeeService_proto = out.File
	file_employeeService_proto_rawDesc = nil
	file_employeeService_proto_goTypes = nil
	file_employeeService_proto_depIdxs = nil
}
