// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: employeeService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmployeeModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" form:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
	// @gotags: json:"name" form:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" form:"name"`
	// @gotags: json:"password" form:"password"
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password" form:"password"`
	// @gotags: json:"tel" form:"tel"
	Tel string `protobuf:"bytes,4,opt,name=tel,proto3" json:"tel" form:"tel"`
	// @gotags: json:"salary" form:"salary"
	Salary float64 `protobuf:"fixed64,5,opt,name=salary,proto3" json:"salary" form:"salary"`
	// @gotags: json:"note" form:"note"
	Note string `protobuf:"bytes,6,opt,name=note,proto3" json:"note" form:"note"`
	// @gotags: json:"level" form:"level"
	Level int32 `protobuf:"varint,7,opt,name=level,proto3" json:"level" form:"level"`
	// @gotags: json:"deleted_at" form:"deleted_at"
	DeletedAt string `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at" form:"deleted_at"`
	// @gotags: json:"account" form:"account"
	Account string `protobuf:"bytes,9,opt,name=account,proto3" json:"account" form:"account"`
}

func (x *EmployeeModel) Reset() {
	*x = EmployeeModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employeeService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeModel) ProtoMessage() {}

func (x *EmployeeModel) ProtoReflect() protoreflect.Message {
	mi := &file_employeeService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeModel.ProtoReflect.Descriptor instead.
func (*EmployeeModel) Descriptor() ([]byte, []int) {
	return file_employeeService_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeeModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmployeeModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmployeeModel) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EmployeeModel) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *EmployeeModel) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *EmployeeModel) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *EmployeeModel) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EmployeeModel) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *EmployeeModel) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type EmployeeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: name:"employee_list" json:"employee_list" form:"employee_list" uri:"employee_list"
	EmployeeList []*EmployeeModel `protobuf:"bytes,1,rep,name=employee_list,json=employeeList,proto3" json:"employee_list" name:"employee_list" form:"employee_list" uri:"employee_list"`
	// @gotags: name:"token" json:"token" form:"token" uri:"token"
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token" name:"token" form:"token" uri:"token"`
}

func (x *EmployeeRequest) Reset() {
	*x = EmployeeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employeeService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeRequest) ProtoMessage() {}

func (x *EmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employeeService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeRequest.ProtoReflect.Descriptor instead.
func (*EmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employeeService_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeRequest) GetEmployeeList() []*EmployeeModel {
	if x != nil {
		return x.EmployeeList
	}
	return nil
}

func (x *EmployeeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EmployeeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: name:"success_list" json:"success_list" form:"success_list" uri:"success_list"
	SuccessList []*EmployeeModel `protobuf:"bytes,1,rep,name=success_list,json=successList,proto3" json:"success_list" name:"success_list" form:"success_list" uri:"success_list"`
	// @gotags: name:"fail_list" json:"fail_list" form:"fail_list" uri:"fail_list"
	FailList []*EmployeeModel `protobuf:"bytes,2,rep,name=fail_list,json=failList,proto3" json:"fail_list" name:"fail_list" form:"fail_list" uri:"fail_list"`
	// @gotags: name:"code" json:"code" form:"code" uri:"code"
	Code uint32 `protobuf:"varint,3,opt,name=code,proto3" json:"code" name:"code" form:"code" uri:"code"`
}

func (x *EmployeeResponse) Reset() {
	*x = EmployeeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employeeService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeResponse) ProtoMessage() {}

func (x *EmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employeeService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeResponse.ProtoReflect.Descriptor instead.
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employeeService_proto_rawDescGZIP(), []int{2}
}

func (x *EmployeeResponse) GetSuccessList() []*EmployeeModel {
	if x != nil {
		return x.SuccessList
	}
	return nil
}

func (x *EmployeeResponse) GetFailList() []*EmployeeModel {
	if x != nil {
		return x.FailList
	}
	return nil
}

func (x *EmployeeResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_employeeService_proto protoreflect.FileDescriptor

var file_employeeService_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x22, 0xdc, 0x01, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x74, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x65, 0x0a, 0x0f, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x0c, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x98, 0x01, 0x0a, 0x10, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0c,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0b, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x66, 0x61, 0x69, 0x6c,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x32, 0x5a, 0x0a, 0x0f, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07,
	0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_employeeService_proto_rawDescOnce sync.Once
	file_employeeService_proto_rawDescData = file_employeeService_proto_rawDesc
)

func file_employeeService_proto_rawDescGZIP() []byte {
	file_employeeService_proto_rawDescOnce.Do(func() {
		file_employeeService_proto_rawDescData = protoimpl.X.CompressGZIP(file_employeeService_proto_rawDescData)
	})
	return file_employeeService_proto_rawDescData
}

var file_employeeService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_employeeService_proto_goTypes = []any{
	(*EmployeeModel)(nil),    // 0: services.EmployeeModel
	(*EmployeeRequest)(nil),  // 1: services.EmployeeRequest
	(*EmployeeResponse)(nil), // 2: services.EmployeeResponse
}
var file_employeeService_proto_depIdxs = []int32{
	0, // 0: services.EmployeeRequest.employee_list:type_name -> services.EmployeeModel
	0, // 1: services.EmployeeResponse.success_list:type_name -> services.EmployeeModel
	0, // 2: services.EmployeeResponse.fail_list:type_name -> services.EmployeeModel
	1, // 3: services.EmployeeService.EmployeeSignup:input_type -> services.EmployeeRequest
	2, // 4: services.EmployeeService.EmployeeSignup:output_type -> services.EmployeeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_employeeService_proto_init() }
func file_employeeService_proto_init() {
	if File_employeeService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_employeeService_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employeeService_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employeeService_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_employeeService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employeeService_proto_goTypes,
		DependencyIndexes: file_employeeService_proto_depIdxs,
		MessageInfos:      file_employeeService_proto_msgTypes,
	}.Build()
	File_employeeService_proto = out.File
	file_employeeService_proto_rawDesc = nil
	file_employeeService_proto_goTypes = nil
	file_employeeService_proto_depIdxs = nil
}
