// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: listService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" form:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
	// @gotags: json:"quantity" form:"quantity"
	Quantity int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity" form:"quantity"`
	// @gotags: json:"total_price" form:"total_price"
	TotalPrice float64 `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price" form:"total_price"`
	// @gotags: json:"time" form:"time"
	Time string `protobuf:"bytes,4,opt,name=time,proto3" json:"time" form:"time"`
	// @gotags: json:"note" form:"note"
	Note string `protobuf:"bytes,5,opt,name=note,proto3" json:"note" form:"note"`
	// @gotags: json:"employee_id" form:"employee_id"
	EmployeeId int32 `protobuf:"varint,6,opt,name=employee_id,json=employeeId,proto3" json:"employee_id" form:"employee_id"`
	// @gotags: json:"msg" form:"msg"
	Msg string `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg" form:"msg"`
}

func (x *ListModel) Reset() {
	*x = ListModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModel) ProtoMessage() {}

func (x *ListModel) ProtoReflect() protoreflect.Message {
	mi := &file_listService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModel.ProtoReflect.Descriptor instead.
func (*ListModel) Descriptor() ([]byte, []int) {
	return file_listService_proto_rawDescGZIP(), []int{0}
}

func (x *ListModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListModel) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ListModel) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *ListModel) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ListModel) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ListModel) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *ListModel) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ListInsertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"list" form:"list"
	List []*ListModel `protobuf:"bytes,1,rep,name=list,proto3" json:"list" form:"list"`
}

func (x *ListInsertRequest) Reset() {
	*x = ListInsertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInsertRequest) ProtoMessage() {}

func (x *ListInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInsertRequest.ProtoReflect.Descriptor instead.
func (*ListInsertRequest) Descriptor() ([]byte, []int) {
	return file_listService_proto_rawDescGZIP(), []int{1}
}

func (x *ListInsertRequest) GetList() []*ListModel {
	if x != nil {
		return x.List
	}
	return nil
}

type ListInsertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"success_list" form:"success_list"
	SuccessList []*ListModel `protobuf:"bytes,1,rep,name=success_list,json=successList,proto3" json:"success_list" form:"success_list"`
	// @gotags: json:"fail_list" form:"fail_list"
	FailList []*ListModel `protobuf:"bytes,2,rep,name=fail_list,json=failList,proto3" json:"fail_list" form:"fail_list"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,3,opt,name=code,proto3" json:"code" form:"code"`
}

func (x *ListInsertResponse) Reset() {
	*x = ListInsertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInsertResponse) ProtoMessage() {}

func (x *ListInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInsertResponse.ProtoReflect.Descriptor instead.
func (*ListInsertResponse) Descriptor() ([]byte, []int) {
	return file_listService_proto_rawDescGZIP(), []int{2}
}

func (x *ListInsertResponse) GetSuccessList() []*ListModel {
	if x != nil {
		return x.SuccessList
	}
	return nil
}

func (x *ListInsertResponse) GetFailList() []*ListModel {
	if x != nil {
		return x.FailList
	}
	return nil
}

func (x *ListInsertResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ListDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"list" form:"list"
	List *ListModel `protobuf:"bytes,1,opt,name=list,proto3" json:"list" form:"list"`
}

func (x *ListDeleteRequest) Reset() {
	*x = ListDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeleteRequest) ProtoMessage() {}

func (x *ListDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeleteRequest.ProtoReflect.Descriptor instead.
func (*ListDeleteRequest) Descriptor() ([]byte, []int) {
	return file_listService_proto_rawDescGZIP(), []int{3}
}

func (x *ListDeleteRequest) GetList() *ListModel {
	if x != nil {
		return x.List
	}
	return nil
}

type ListDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"success" form:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success" form:"success"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code" form:"code"`
}

func (x *ListDeleteResponse) Reset() {
	*x = ListDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeleteResponse) ProtoMessage() {}

func (x *ListDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeleteResponse.ProtoReflect.Descriptor instead.
func (*ListDeleteResponse) Descriptor() ([]byte, []int) {
	return file_listService_proto_rawDescGZIP(), []int{4}
}

func (x *ListDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDeleteResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ListUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"list" form:"list"
	List *ListModel `protobuf:"bytes,1,opt,name=list,proto3" json:"list" form:"list"`
}

func (x *ListUpdateRequest) Reset() {
	*x = ListUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpdateRequest) ProtoMessage() {}

func (x *ListUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpdateRequest.ProtoReflect.Descriptor instead.
func (*ListUpdateRequest) Descriptor() ([]byte, []int) {
	return file_listService_proto_rawDescGZIP(), []int{5}
}

func (x *ListUpdateRequest) GetList() *ListModel {
	if x != nil {
		return x.List
	}
	return nil
}

type ListUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"success" form:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success" form:"success"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code" form:"code"`
	// @gotags: json:"msg" form:"msg"
	Msg string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg" form:"msg"`
}

func (x *ListUpdateResponse) Reset() {
	*x = ListUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpdateResponse) ProtoMessage() {}

func (x *ListUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpdateResponse.ProtoReflect.Descriptor instead.
func (*ListUpdateResponse) Descriptor() ([]byte, []int) {
	return file_listService_proto_rawDescGZIP(), []int{6}
}

func (x *ListUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListUpdateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListUpdateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ListSelectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSelectRequest) Reset() {
	*x = ListSelectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSelectRequest) ProtoMessage() {}

func (x *ListSelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSelectRequest.ProtoReflect.Descriptor instead.
func (*ListSelectRequest) Descriptor() ([]byte, []int) {
	return file_listService_proto_rawDescGZIP(), []int{7}
}

type ListSelectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"list" form:"list"
	List []*ListModel `protobuf:"bytes,1,rep,name=list,proto3" json:"list" form:"list"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code" form:"code"`
}

func (x *ListSelectResponse) Reset() {
	*x = ListSelectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSelectResponse) ProtoMessage() {}

func (x *ListSelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSelectResponse.ProtoReflect.Descriptor instead.
func (*ListSelectResponse) Descriptor() ([]byte, []int) {
	return file_listService_proto_rawDescGZIP(), []int{8}
}

func (x *ListSelectResponse) GetList() []*ListModel {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListSelectResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_listService_proto protoreflect.FileDescriptor

var file_listService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0xb3, 0x01,
	0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x3c, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x22, 0x92, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x0b, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x30, 0x0a, 0x09, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x3c, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x3c, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x13, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x51, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x32, 0xb1, 0x02, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x0a, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_listService_proto_rawDescOnce sync.Once
	file_listService_proto_rawDescData = file_listService_proto_rawDesc
)

func file_listService_proto_rawDescGZIP() []byte {
	file_listService_proto_rawDescOnce.Do(func() {
		file_listService_proto_rawDescData = protoimpl.X.CompressGZIP(file_listService_proto_rawDescData)
	})
	return file_listService_proto_rawDescData
}

var file_listService_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_listService_proto_goTypes = []any{
	(*ListModel)(nil),          // 0: services.ListModel
	(*ListInsertRequest)(nil),  // 1: services.ListInsertRequest
	(*ListInsertResponse)(nil), // 2: services.ListInsertResponse
	(*ListDeleteRequest)(nil),  // 3: services.ListDeleteRequest
	(*ListDeleteResponse)(nil), // 4: services.ListDeleteResponse
	(*ListUpdateRequest)(nil),  // 5: services.ListUpdateRequest
	(*ListUpdateResponse)(nil), // 6: services.ListUpdateResponse
	(*ListSelectRequest)(nil),  // 7: services.ListSelectRequest
	(*ListSelectResponse)(nil), // 8: services.ListSelectResponse
}
var file_listService_proto_depIdxs = []int32{
	0,  // 0: services.ListInsertRequest.list:type_name -> services.ListModel
	0,  // 1: services.ListInsertResponse.success_list:type_name -> services.ListModel
	0,  // 2: services.ListInsertResponse.fail_list:type_name -> services.ListModel
	0,  // 3: services.ListDeleteRequest.list:type_name -> services.ListModel
	0,  // 4: services.ListUpdateRequest.list:type_name -> services.ListModel
	0,  // 5: services.ListSelectResponse.list:type_name -> services.ListModel
	1,  // 6: services.ListService.InsertList:input_type -> services.ListInsertRequest
	3,  // 7: services.ListService.DeleteList:input_type -> services.ListDeleteRequest
	5,  // 8: services.ListService.UpdateList:input_type -> services.ListUpdateRequest
	7,  // 9: services.ListService.SelectList:input_type -> services.ListSelectRequest
	2,  // 10: services.ListService.InsertList:output_type -> services.ListInsertResponse
	4,  // 11: services.ListService.DeleteList:output_type -> services.ListDeleteResponse
	6,  // 12: services.ListService.UpdateList:output_type -> services.ListUpdateResponse
	8,  // 13: services.ListService.SelectList:output_type -> services.ListSelectResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_listService_proto_init() }
func file_listService_proto_init() {
	if File_listService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_listService_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listService_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListInsertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listService_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListInsertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listService_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listService_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listService_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listService_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listService_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListSelectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listService_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListSelectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_listService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listService_proto_goTypes,
		DependencyIndexes: file_listService_proto_depIdxs,
		MessageInfos:      file_listService_proto_msgTypes,
	}.Build()
	File_listService_proto = out.File
	file_listService_proto_rawDesc = nil
	file_listService_proto_goTypes = nil
	file_listService_proto_depIdxs = nil
}
