// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: authService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" form:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
}

func (x *TokenRegister) Reset() {
	*x = TokenRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRegister) ProtoMessage() {}

func (x *TokenRegister) ProtoReflect() protoreflect.Message {
	mi := &file_authService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRegister.ProtoReflect.Descriptor instead.
func (*TokenRegister) Descriptor() ([]byte, []int) {
	return file_authService_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRegister) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TokenDiscovery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" form:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
}

func (x *TokenDiscovery) Reset() {
	*x = TokenDiscovery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenDiscovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDiscovery) ProtoMessage() {}

func (x *TokenDiscovery) ProtoReflect() protoreflect.Message {
	mi := &file_authService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDiscovery.ProtoReflect.Descriptor instead.
func (*TokenDiscovery) Descriptor() ([]byte, []int) {
	return file_authService_proto_rawDescGZIP(), []int{1}
}

func (x *TokenDiscovery) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TokenAuthorization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"token" form:"token"
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token" form:"token"`
}

func (x *TokenAuthorization) Reset() {
	*x = TokenAuthorization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAuthorization) ProtoMessage() {}

func (x *TokenAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_authService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAuthorization.ProtoReflect.Descriptor instead.
func (*TokenAuthorization) Descriptor() ([]byte, []int) {
	return file_authService_proto_rawDescGZIP(), []int{2}
}

func (x *TokenAuthorization) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenRegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" form:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
}

func (x *TokenRegisterReq) Reset() {
	*x = TokenRegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRegisterReq) ProtoMessage() {}

func (x *TokenRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_authService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRegisterReq.ProtoReflect.Descriptor instead.
func (*TokenRegisterReq) Descriptor() ([]byte, []int) {
	return file_authService_proto_rawDescGZIP(), []int{3}
}

func (x *TokenRegisterReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TokenRegisterRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"token" form:"token"
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token" form:"token"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code" form:"code"`
}

func (x *TokenRegisterRsp) Reset() {
	*x = TokenRegisterRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRegisterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRegisterRsp) ProtoMessage() {}

func (x *TokenRegisterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_authService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRegisterRsp.ProtoReflect.Descriptor instead.
func (*TokenRegisterRsp) Descriptor() ([]byte, []int) {
	return file_authService_proto_rawDescGZIP(), []int{4}
}

func (x *TokenRegisterRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenRegisterRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type TokenDiscoveryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" form:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
}

func (x *TokenDiscoveryReq) Reset() {
	*x = TokenDiscoveryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenDiscoveryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDiscoveryReq) ProtoMessage() {}

func (x *TokenDiscoveryReq) ProtoReflect() protoreflect.Message {
	mi := &file_authService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDiscoveryReq.ProtoReflect.Descriptor instead.
func (*TokenDiscoveryReq) Descriptor() ([]byte, []int) {
	return file_authService_proto_rawDescGZIP(), []int{5}
}

func (x *TokenDiscoveryReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TokenDiscoveryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"token" form:"token"
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token" form:"token"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code" form:"code"`
}

func (x *TokenDiscoveryRsp) Reset() {
	*x = TokenDiscoveryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenDiscoveryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDiscoveryRsp) ProtoMessage() {}

func (x *TokenDiscoveryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_authService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDiscoveryRsp.ProtoReflect.Descriptor instead.
func (*TokenDiscoveryRsp) Descriptor() ([]byte, []int) {
	return file_authService_proto_rawDescGZIP(), []int{6}
}

func (x *TokenDiscoveryRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenDiscoveryRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type TokenAuthorizationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"token" form:"token"
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token" form:"token"`
}

func (x *TokenAuthorizationReq) Reset() {
	*x = TokenAuthorizationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenAuthorizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAuthorizationReq) ProtoMessage() {}

func (x *TokenAuthorizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_authService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAuthorizationReq.ProtoReflect.Descriptor instead.
func (*TokenAuthorizationReq) Descriptor() ([]byte, []int) {
	return file_authService_proto_rawDescGZIP(), []int{7}
}

func (x *TokenAuthorizationReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenAuthorizationRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"level" form:"level"
	Level int32 `protobuf:"varint,1,opt,name=level,proto3" json:"level" form:"level"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code" form:"code"`
}

func (x *TokenAuthorizationRsp) Reset() {
	*x = TokenAuthorizationRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenAuthorizationRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAuthorizationRsp) ProtoMessage() {}

func (x *TokenAuthorizationRsp) ProtoReflect() protoreflect.Message {
	mi := &file_authService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAuthorizationRsp.ProtoReflect.Descriptor instead.
func (*TokenAuthorizationRsp) Descriptor() ([]byte, []int) {
	return file_authService_proto_rawDescGZIP(), []int{8}
}

func (x *TokenAuthorizationRsp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *TokenAuthorizationRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_authService_proto protoreflect.FileDescriptor

var file_authService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x1f, 0x0a,
	0x0d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20,
	0x0a, 0x0e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2a, 0x0a, 0x12, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x22, 0x0a, 0x10,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3c, 0x0a, 0x10, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x23,
	0x0a, 0x11, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x11, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x2d, 0x0a, 0x15, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x41, 0x0a, 0x15, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x32, 0xf5, 0x01, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x49, 0x0a,
	0x0d, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x73, 0x70, 0x12, 0x52, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authService_proto_rawDescOnce sync.Once
	file_authService_proto_rawDescData = file_authService_proto_rawDesc
)

func file_authService_proto_rawDescGZIP() []byte {
	file_authService_proto_rawDescOnce.Do(func() {
		file_authService_proto_rawDescData = protoimpl.X.CompressGZIP(file_authService_proto_rawDescData)
	})
	return file_authService_proto_rawDescData
}

var file_authService_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_authService_proto_goTypes = []any{
	(*TokenRegister)(nil),         // 0: services.TokenRegister
	(*TokenDiscovery)(nil),        // 1: services.TokenDiscovery
	(*TokenAuthorization)(nil),    // 2: services.TokenAuthorization
	(*TokenRegisterReq)(nil),      // 3: services.TokenRegisterReq
	(*TokenRegisterRsp)(nil),      // 4: services.TokenRegisterRsp
	(*TokenDiscoveryReq)(nil),     // 5: services.TokenDiscoveryReq
	(*TokenDiscoveryRsp)(nil),     // 6: services.TokenDiscoveryRsp
	(*TokenAuthorizationReq)(nil), // 7: services.TokenAuthorizationReq
	(*TokenAuthorizationRsp)(nil), // 8: services.TokenAuthorizationRsp
}
var file_authService_proto_depIdxs = []int32{
	3, // 0: services.AuthService.RegisterToken:input_type -> services.TokenRegisterReq
	5, // 1: services.AuthService.DiscoverToken:input_type -> services.TokenDiscoveryReq
	7, // 2: services.AuthService.AuthorizeToken:input_type -> services.TokenAuthorizationReq
	4, // 3: services.AuthService.RegisterToken:output_type -> services.TokenRegisterRsp
	6, // 4: services.AuthService.DiscoverToken:output_type -> services.TokenDiscoveryRsp
	8, // 5: services.AuthService.AuthorizeToken:output_type -> services.TokenAuthorizationRsp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authService_proto_init() }
func file_authService_proto_init() {
	if File_authService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authService_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TokenRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authService_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TokenDiscovery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authService_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TokenAuthorization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authService_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TokenRegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authService_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TokenRegisterRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authService_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TokenDiscoveryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authService_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TokenDiscoveryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authService_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TokenAuthorizationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authService_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*TokenAuthorizationRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authService_proto_goTypes,
		DependencyIndexes: file_authService_proto_depIdxs,
		MessageInfos:      file_authService_proto_msgTypes,
	}.Build()
	File_authService_proto = out.File
	file_authService_proto_rawDesc = nil
	file_authService_proto_goTypes = nil
	file_authService_proto_depIdxs = nil
}
