// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: detailService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetailModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"id" form:"id"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
	// @gotags: json:"product_id" form:"product_id"
	ProductId int32 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id" form:"product_id"`
	// @gotags: json:"quantity" form:"quantity"
	Quantity int32 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity" form:"quantity"`
	// @gotags: json:"total_price" form:"total_price"
	TotalPrice float64 `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price" form:"total_price"`
	// @gotags: json:"note" form:"note"
	Note string `protobuf:"bytes,5,opt,name=note,proto3" json:"note" form:"note"`
	// @gotags: json:"list_id" form:"list_id"
	ListId int32 `protobuf:"varint,6,opt,name=list_id,json=listId,proto3" json:"list_id" form:"list_id"`
	// @gotags: json:"msg" form:"msg"
	Msg string `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg" form:"msg"`
}

func (x *DetailModel) Reset() {
	*x = DetailModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detailService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailModel) ProtoMessage() {}

func (x *DetailModel) ProtoReflect() protoreflect.Message {
	mi := &file_detailService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailModel.ProtoReflect.Descriptor instead.
func (*DetailModel) Descriptor() ([]byte, []int) {
	return file_detailService_proto_rawDescGZIP(), []int{0}
}

func (x *DetailModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DetailModel) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DetailModel) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DetailModel) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *DetailModel) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *DetailModel) GetListId() int32 {
	if x != nil {
		return x.ListId
	}
	return 0
}

func (x *DetailModel) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DetailInsertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"list" form:"list"
	List []*DetailModel `protobuf:"bytes,1,rep,name=list,proto3" json:"list" form:"list"`
}

func (x *DetailInsertRequest) Reset() {
	*x = DetailInsertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detailService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailInsertRequest) ProtoMessage() {}

func (x *DetailInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detailService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailInsertRequest.ProtoReflect.Descriptor instead.
func (*DetailInsertRequest) Descriptor() ([]byte, []int) {
	return file_detailService_proto_rawDescGZIP(), []int{1}
}

func (x *DetailInsertRequest) GetList() []*DetailModel {
	if x != nil {
		return x.List
	}
	return nil
}

type DetailInsertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"success_list" form:"success_list"
	SuccessList []*DetailModel `protobuf:"bytes,1,rep,name=success_list,json=successList,proto3" json:"success_list" form:"success_list"`
	// @gotags: json:"fail_list" form:"fail_list"
	FailList []*DetailModel `protobuf:"bytes,2,rep,name=fail_list,json=failList,proto3" json:"fail_list" form:"fail_list"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,3,opt,name=code,proto3" json:"code" form:"code"`
}

func (x *DetailInsertResponse) Reset() {
	*x = DetailInsertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detailService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailInsertResponse) ProtoMessage() {}

func (x *DetailInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detailService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailInsertResponse.ProtoReflect.Descriptor instead.
func (*DetailInsertResponse) Descriptor() ([]byte, []int) {
	return file_detailService_proto_rawDescGZIP(), []int{2}
}

func (x *DetailInsertResponse) GetSuccessList() []*DetailModel {
	if x != nil {
		return x.SuccessList
	}
	return nil
}

func (x *DetailInsertResponse) GetFailList() []*DetailModel {
	if x != nil {
		return x.FailList
	}
	return nil
}

func (x *DetailInsertResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DetailDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"detail" form:"detail"
	Detail *DetailModel `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail" form:"detail"`
}

func (x *DetailDeleteRequest) Reset() {
	*x = DetailDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detailService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailDeleteRequest) ProtoMessage() {}

func (x *DetailDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detailService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailDeleteRequest.ProtoReflect.Descriptor instead.
func (*DetailDeleteRequest) Descriptor() ([]byte, []int) {
	return file_detailService_proto_rawDescGZIP(), []int{3}
}

func (x *DetailDeleteRequest) GetDetail() *DetailModel {
	if x != nil {
		return x.Detail
	}
	return nil
}

type DetailDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"success" form:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success" form:"success"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code" form:"code"`
	// @gotags: json:"msg" form:"msg"
	Msg string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg" form:"msg"`
}

func (x *DetailDeleteResponse) Reset() {
	*x = DetailDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detailService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailDeleteResponse) ProtoMessage() {}

func (x *DetailDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detailService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailDeleteResponse.ProtoReflect.Descriptor instead.
func (*DetailDeleteResponse) Descriptor() ([]byte, []int) {
	return file_detailService_proto_rawDescGZIP(), []int{4}
}

func (x *DetailDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetailDeleteResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DetailDeleteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DetailUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"detail" form:"detail"
	Detail *DetailModel `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail" form:"detail"`
}

func (x *DetailUpdateRequest) Reset() {
	*x = DetailUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detailService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailUpdateRequest) ProtoMessage() {}

func (x *DetailUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detailService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailUpdateRequest.ProtoReflect.Descriptor instead.
func (*DetailUpdateRequest) Descriptor() ([]byte, []int) {
	return file_detailService_proto_rawDescGZIP(), []int{5}
}

func (x *DetailUpdateRequest) GetDetail() *DetailModel {
	if x != nil {
		return x.Detail
	}
	return nil
}

type DetailUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"success" form:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success" form:"success"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code" form:"code"`
	// @gotags: json:"msg" form:"msg"
	Msg string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg" form:"msg"`
}

func (x *DetailUpdateResponse) Reset() {
	*x = DetailUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detailService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailUpdateResponse) ProtoMessage() {}

func (x *DetailUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detailService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailUpdateResponse.ProtoReflect.Descriptor instead.
func (*DetailUpdateResponse) Descriptor() ([]byte, []int) {
	return file_detailService_proto_rawDescGZIP(), []int{6}
}

func (x *DetailUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetailUpdateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DetailUpdateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DetailSelectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DetailSelectRequest) Reset() {
	*x = DetailSelectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detailService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailSelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailSelectRequest) ProtoMessage() {}

func (x *DetailSelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detailService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailSelectRequest.ProtoReflect.Descriptor instead.
func (*DetailSelectRequest) Descriptor() ([]byte, []int) {
	return file_detailService_proto_rawDescGZIP(), []int{7}
}

type DetailSelectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"detail_list" form:"detail_list"
	DetailList []*DetailModel `protobuf:"bytes,1,rep,name=detail_list,json=detailList,proto3" json:"detail_list" form:"detail_list"`
	// @gotags: json:"code" form:"code"
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code" form:"code"`
}

func (x *DetailSelectResponse) Reset() {
	*x = DetailSelectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detailService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailSelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailSelectResponse) ProtoMessage() {}

func (x *DetailSelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detailService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailSelectResponse.ProtoReflect.Descriptor instead.
func (*DetailSelectResponse) Descriptor() ([]byte, []int) {
	return file_detailService_proto_rawDescGZIP(), []int{8}
}

func (x *DetailSelectResponse) GetDetailList() []*DetailModel {
	if x != nil {
		return x.DetailList
	}
	return nil
}

func (x *DetailSelectResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_detailService_proto protoreflect.FileDescriptor

var file_detailService_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22,
	0xb8, 0x01, 0x0a, 0x0b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x40, 0x0a, 0x13, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x29, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x98, 0x01, 0x0a,
	0x14, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x0b, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x32, 0x0a, 0x09, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x44, 0x0a, 0x13, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d,
	0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x56, 0x0a,
	0x14, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x44, 0x0a, 0x13, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x06,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x56, 0x0a, 0x14, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x62, 0x0a, 0x14, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0a,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0xcb,
	0x02, 0x0a, 0x0d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4d, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4d, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d,
	0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a,
	0x0c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_detailService_proto_rawDescOnce sync.Once
	file_detailService_proto_rawDescData = file_detailService_proto_rawDesc
)

func file_detailService_proto_rawDescGZIP() []byte {
	file_detailService_proto_rawDescOnce.Do(func() {
		file_detailService_proto_rawDescData = protoimpl.X.CompressGZIP(file_detailService_proto_rawDescData)
	})
	return file_detailService_proto_rawDescData
}

var file_detailService_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_detailService_proto_goTypes = []any{
	(*DetailModel)(nil),          // 0: services.DetailModel
	(*DetailInsertRequest)(nil),  // 1: services.DetailInsertRequest
	(*DetailInsertResponse)(nil), // 2: services.DetailInsertResponse
	(*DetailDeleteRequest)(nil),  // 3: services.DetailDeleteRequest
	(*DetailDeleteResponse)(nil), // 4: services.DetailDeleteResponse
	(*DetailUpdateRequest)(nil),  // 5: services.DetailUpdateRequest
	(*DetailUpdateResponse)(nil), // 6: services.DetailUpdateResponse
	(*DetailSelectRequest)(nil),  // 7: services.DetailSelectRequest
	(*DetailSelectResponse)(nil), // 8: services.DetailSelectResponse
}
var file_detailService_proto_depIdxs = []int32{
	0,  // 0: services.DetailInsertRequest.list:type_name -> services.DetailModel
	0,  // 1: services.DetailInsertResponse.success_list:type_name -> services.DetailModel
	0,  // 2: services.DetailInsertResponse.fail_list:type_name -> services.DetailModel
	0,  // 3: services.DetailDeleteRequest.detail:type_name -> services.DetailModel
	0,  // 4: services.DetailUpdateRequest.detail:type_name -> services.DetailModel
	0,  // 5: services.DetailSelectResponse.detail_list:type_name -> services.DetailModel
	1,  // 6: services.DetailService.InsertDetail:input_type -> services.DetailInsertRequest
	3,  // 7: services.DetailService.DeleteDetail:input_type -> services.DetailDeleteRequest
	5,  // 8: services.DetailService.UpdateDetail:input_type -> services.DetailUpdateRequest
	7,  // 9: services.DetailService.SelectDetail:input_type -> services.DetailSelectRequest
	2,  // 10: services.DetailService.InsertDetail:output_type -> services.DetailInsertResponse
	4,  // 11: services.DetailService.DeleteDetail:output_type -> services.DetailDeleteResponse
	6,  // 12: services.DetailService.UpdateDetail:output_type -> services.DetailUpdateResponse
	8,  // 13: services.DetailService.SelectDetail:output_type -> services.DetailSelectResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_detailService_proto_init() }
func file_detailService_proto_init() {
	if File_detailService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_detailService_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DetailModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detailService_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DetailInsertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detailService_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DetailInsertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detailService_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DetailDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detailService_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DetailDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detailService_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DetailUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detailService_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DetailUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detailService_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DetailSelectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detailService_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DetailSelectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_detailService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_detailService_proto_goTypes,
		DependencyIndexes: file_detailService_proto_depIdxs,
		MessageInfos:      file_detailService_proto_msgTypes,
	}.Build()
	File_detailService_proto = out.File
	file_detailService_proto_rawDesc = nil
	file_detailService_proto_goTypes = nil
	file_detailService_proto_depIdxs = nil
}
