version: '3.8'

services:
  mysql_database_lesson:
    image: mysql:8.0
    container_name: mysql_database_lesson
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_lesson
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    networks:
      - database_design_network
  redis-6379: # 服务名称
    image: redis # 创建容器时所需的镜像
    container_name: redis-6379 # 容器名称
    network_mode: "bridge" # host 网络模式
    command: redis-server /usr/local/etc/redis/redis.conf # 覆盖容器启动后默认执行的命令
    restart: always # 容器总是重新启动
    networks:
      - database_design_network

  database_lesson:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=database_lesson
    image: database_lesson:latest
    container_name: database_lesson
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql_database_lesson
    ports:
      - "4000:4000"
    restart: always
    networks:
      - database_design_network

networks:
  database_design_network:
