version: '3.8'

services:
  mysql_database_lesson:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_lesson
    volumes:
      - "$PWD/consts/mysql/init:/docker-entrypoint-initdb.d"

  database_lesson:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=database_lesson
    image: database_lesson:latest
    container_name: database_lesson
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql_database_lesson
      - etcd
    ports:
      - "4000:4000"