mysql:
  host: "localhost"
  port: "3306"
  db: database_lesson
  user: root
  password: root
  log_level: "test"


logger:
  level: info
  prefix: '[Gin_Project]'
  director: log
  show_line: true
  log_in_console: true

system:
  host: "0.0.0.0"
  port: "4000"
  env: "release"

redis:
  Addr: "redis-6379:6379"
  Password: ""
  DB: 0
  PoolSize: 15
  MinIdleConns: 10